nb_of_topics: 3
topic_1:
  name: imu
  topic_name: /imu/data
  min_freq: 90

topic_2:
  name: depth_camera
  topic_name: /d435/depth/color/points
  min_freq: 3

topic_3:
  name: gps
  topic_name: /fix
  min_freq: 0.5