footprint: [[0.6225, 0.5425], [-0.6225, 0.5425], [-0.6225, -0.5425], [0.6225, -0.5425]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 1.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
#static:
#    map_topic: /map
#    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser_scan
    laser_scan: {data_type: LaserScan, topic: /obstacle_detector/scan, marking: true, clearing: true, sensor_frame: base_link} 

inflation_layer:
    inflation_radius: 1.0